import type { Metadata } from 'next'
import { inter } from '@/shared/shared'
import '../styles/globals.css'

export const metadata: Metadata = {
  title: 'Sky - Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
